module.exports = {
	getDataSuccess: 'Get Data Successfully',
	alreadyExited: "Already Exiting Value",
	ext_Account: "Already Exiting Account, Please Login",
	alreadyVerified: "Already Verifed",
	alreadyExitedJob: "Already Exiting Job",
	showedDataSuccess: "Seekers Showed",
	tokenSended: "Token Sended Successfully",
	showedDataFailure: "Show Data Failure",
	updateDataFailure: "Update Data Failure",
	notUpdated: "Not updated",
	updateDataSuccess: "Update Data Successfully",
	Verified: 'Verifed Successfully',
	deleteDataSuccess: "Delete Data Successfuly",
	deleteDataFailure: "Delete Data Failure",
	truncateSuccess: 'Truncate Table Successfully',
	truncateFailure: 'Truncate Table Failure',
	getDataFailure: 'Get Data Failure',
	jobPosted: "Job Posted Successfully",
	unauthorized: "Unauthorized Request.",
	passwordsended: "Password sent Registered Email",
	not_unique: 'fields are not Unique',
	tokenVerifed: "Token Verified",
	userNotFound: "User Not Founded",
	createdSuccess: "Created Successfully",
	notCreated: "user Creating Failure",
	errInCreate: "Error in Creating ",
	errorInFindingAll: "Error in Finding all data",
	errorInFindingId: "Error in Finding Id",
	changedPassword: "password changed Successfully",
	notchangedPass: "password was not changed",
	errorInFindOne: "Error in FindOne",
	errorInFindAllMatch: "Error in FindAllMatch",
	errorInUpdating: "Error in Updating",
	errorInDeleting: "Error in Deleting",
	errorInSendingEmail: 'Error in Sending Email',
	errorInSendingSMS: 'Error in Sending SMS',
	SendingEmailFailure: 'Email Sended Failure',
	SendingEmailSuccess: 'Email Sended Successfully',
	SendingSMSFailure: 'SMS Sended Failure',
	SendingSMSSuccess: 'SMS Sended Successfully',
	seekerUpdated: "Seeker Updated Successfully",
	seekerNotUpdated: "Seeker not update",
	seekerFounded: "seeker Founded",
	notFound: "Not Found",
	verificationFail: "Verification Failure",
	noSeeker: "No Seekers",
	deletedData: "Deleted Successfully",
	notDeleted: "Not Deleted",
	seekerNotFound: "Seeker Not Found",
	badRequest: "Invalid Data Provided",
	Not_Unique: "not_unique",
	loginSuccess: "Login Successfully",
	dashboard: "Token has Verifed",
	loginFailure: "Login Failure",
	registerSuccess: "Register Successfully",
	passwordIncorrect: "password is Incorrect",
	tokenSended: "Token sended Successfully",
	registerFailure: "Register Failure",
	registerAlready: "Already Register",
	invalidOTP: "Invalid OTP",
	giveInput: "Give the all Input",
	unauthorized: "Unauthorized Request",
	tokenVerifed: "Token Verifed Successfully",
	otpResended: "OTP Resended Successfully",
	otpSended: "OTP Sended Successfully",
	otpNotSended: "OTP not sended",
	otpNotUpdated: "OTP not Updated",
	ext_email: "already exiting Email Id",
	ext_email_mobile: "already exiting Email Id and Mobile Number",
	ext_mobile: "already exiting Mobile Number",
};
