module.exports = {
	getDataSuccess : 'Get Data Successfully',
	alreadyExited:"Already Exiting Value",
	showedDataSuccess:"Seekers Showed",
	tokenSended:"Token Sended Successfully",
	showedDataFailure: "Show Data Failure",
	updateDataFailure:"Update Data Failure",
	updateDataSuccess:"Update Data Successfully",
	deleteDataSuccess:"Delete Data Successfuly",
	deleteDataFailure:"Delete Data Failure",
	getDataFailure : 'Get Data Failure',
	unauthorized: "Unauthorized Request.",
	not_unique:'fields are not Unique',
	tokenVerifed:"Token Verified",
	createdSuccess: "Created Successfully",
	notCreated: "user Creating Failure",
	errInCreate: "Error in Creating ",
	errorInFindingAll: "Error in Finding all data",
	errorInFindingId: "Error in Finding Id",
	errorInFindOne: "Error in FindOne",
	errorInFindAllMatch: "Error in FindAllMatch",
	errorInUpdating: "Error in Updating",
	errorInDeleting: "Error in Deleting",
	seekerUpdated: "Seeker Updated Successfully",
	seekerNotUpdated: "Seeker not update",
	seekerFounded: "seeker Founded",
	notFound: "Not Found",
	verificationFail:"Verification Failure",
	noSeeker: "No Seekers",
	deletedData: "Deleted Successfully",
	notDeleted: "Not Deleted",
	seekerNotFound: "Seeker Not Found",
	badRequest: "Invalid Data Provided",
	Not_Unique: "not_unique",
	loginSuccess: "Login Successfully",
	dashboard: "Token has Verifed",
	loginFailure: "Login Failure",
	registerSuccess: "Register Successfully",
	passwordIncorrect: "password is Incorrect",
	tokenSended: "Token sended Successfully",
	registerFailure: "Register Failure",
	registerAlready: "Already Register",
	invalidOTP: "Invalid OTP",
	giveInput: "Give the all Input",
	unauthorized: "Unauthorized Request",
	tokenVerifed: "Token Verifed Successfully",
	otpResended: "OTP Resended Successfully",
	otpSended: "OTP Sended Successfully",
	otpNotSended: "OTP not sended",
	otpNotUpdated: "OTP not Updated",
	ext_email: "already exiting Email Id",
	ext_mobile: "already exiting Mobile Number",
};
