module.exports = {
	createdSuccess: "Created Successfully",
	notCreated:"user Creating Failure",
	errInCreate:"Error in Creating ",
	errorInFindingAll:"Error in Finding all data",
	errorInFindingId:"Error in Finding Id",
	errorInFindOne:"Error in FindOne",
	errorInFindAllMatch:"Error in FindAllMatch",
	errorInUpdating: "Error in Updating",
	errorInDeleting:"Error in Deleting",
	seekerUpdated:"Seeker Updated Successfully",
	seekerNotUpdated:"Seeker not update",
	seekerFounded:"seeker Founded",
	notFound: "Not Found",
	userNotFound: "User Not Founded",
	noSeeker:"No Seekers",
	deletedData:"Deleted Successfully",
	alreadyExited: "Already Exiting Value",
	alreadyExitedJob: "Already Exiting Job",
	jobPosted:"Job Posted Successfully",
	notDeleted:"Not Deleted",
	getDataSuccess: 'get Data Success',
	seekerNotFound: "Seeker Not Found",
	badRequest: "Invalid Data Provided",
	Not_Unique: "not_unique",
	loginSuccess:"Login Successfully",
	dashboard:"This is dashboard",
	notchangedPass:"password was not changed",
	changedPassword:"password changed Successfully",
	loginFailure:"Login Failure",
	passwordsended: "Password is sended to Email",
	registerSuccess:"Register Successfully",
	passwordIncorrect:"password is Incorrect",
	tokenSended:"Token sended Successfully",
	registerFailure:"Register Failure",
	registerAlready:"Already Register",
	invalidOTP:"Invalid OTP",
	giveInput:"Give the all Input",
	unauthorized: "Unauthorized Request",
	tokenVerifed: "Token Verifed Successfully",
	otpResended: "OTP Resended",
	otpSended:"OTP Sended Successfully",
	otpNotSended:"OTP not sended",
	otpNotUpdated:"OTP not Updated",
	ext_email: "already exiting Email Id",
	ext_mobile: "already exiting Mobile Number",

};
